-- apaga.sql
DROP TABLE fato_entrega_produto CASCADE CONSTRAINTS;
DROP TABLE dim_pedido CASCADE CONSTRAINTS;
DROP TABLE dim_entregador CASCADE CONSTRAINTS;
DROP TABLE dim_data CASCADE CONSTRAINTS;
DROP TABLE dim_produto CASCADE CONSTRAINTS;
DROP TABLE dim_subcategoria CASCADE CONSTRAINTS;
DROP TABLE dim_categoria CASCADE CONSTRAINTS;
DROP TABLE dim_centro_distribuicao CASCADE CONSTRAINTS;
DROP TABLE dim_cliente CASCADE CONSTRAINTS;
DROP TABLE dim_logradouro CASCADE CONSTRAINTS;
DROP TABLE dim_bairro CASCADE CONSTRAINTS;
DROP TABLE dim_cidade CASCADE CONSTRAINTS;
DROP TABLE dim_estado CASCADE CONSTRAINTS;
DROP TABLE dim_regiao CASCADE CONSTRAINTS;